### PR TITLE
[ADD] Support dilated convolutions

### LINKED ISSUE #21: Support dilated convolutions
(follow-up from #34)

The current version of [`_extract_patches`](https://github.com/f-dangel/singd/blob/4c24d3552f6beedd59d33b7a94225d4e4ba4b455/singd/optim/utils.py#L12-L18) does not take into account the `dilation` of a convolution. Supporting this is not urgent as I am not aware of any `torchvision` CNN that uses dilated convolution. But we should fix this long-term because the code might run without errors.

### PR DESCRIPTION
**Pull request by f-dangel**
Resolves #21.

### CODE REVIEW

**Review by runame — APPROVED** [review]
LGTM. Btw, have you looked at the implementation of `_extract_patches` in ASDL? Kazuki's [custom function](https://github.com/kazukiosawa/asdl/blob/master/asdl/utils.py#L51-L71) only supports `dilation=1` though.

**Comment by f-dangel** [comment]
I'm not sure how Kazuki's version works, but he seems to be using [`Tensor.unfold`](https://pytorch.org/docs/stable/generated/torch.Tensor.unfold.html), which is different from `nn.functional.unfold`. Maybe this trick has better performance?

**Comment by runame** [comment]
Yeah, I think that is the intention behind not using `nn.functional.unfold`. Anyway, we can look into improving the performance of `_extract_patches` at a later point, I can create an issue for this. We will also want to use your implementation in `einconv` when using KFAC-reduce for `Conv2d` modules.

**Comment by f-dangel** [comment]
Sounds good. Might be worth to measure some times first.

Regarding the TN stuff, I need to think about an interface. Maybe we can just support a `StructuredMatrix @ TensorNetwork`.

**Pull request merged**
